# name: CI
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: install packages
#         run: make install
#       - name: lint
#         run: make lint
#       - name: test
#         run: make test
#       - name: format
#         run: make format
#       - name: deploy
#         run: make deploy


name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install packages
        run: make install
        
      - name: Install PySpark dependencies
        run: |
          pip install pyspark pytest pytest-cov pandas
          
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          
      - name: lint
        run: make lint
        
      - name: test
        run: make test
        
      - name: format
        run: make format
        
      - name: deploy
        run: make deploy